"""
Views for the recipe APIs
"""

from drf_spectacular.utils import (
    extend_schema_view,
    extend_schema,
    OpenApiParameter,
    OpenApiTypes,
)
from rest_framework import viewsets, mixins, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

from core.models import Recipe, Tag, Ingredient
from recipe import serializers


@extend_schema_view(
    list=extend_schema(
        parameters=[
            OpenApiParameter(
                "tags",
                OpenApiTypes.STR,
                description="Comma separated list of IDs to filter",
            ),
            OpenApiParameter(
                "ingredients",
                OpenApiTypes.STR,
                description="Comma separated list of IDs to filter",
            ),
        ]
    )
)  # extend the autogenerated schema
class RecipeViewSet(viewsets.ModelViewSet):
    # ModelViewSet is specifically for Django models
    """View for manage recipe APIs (generates multiple endpoints)"""
    serializer_class = serializers.RecipeDetailSerializer
    queryset = (
        Recipe.objects.all()
    )  # The objects that are available for this viewset, here we get all recipes in the DB

    # Handling the authentication stuff
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]

    def _params_to_ints(self, qs):
        """Convert a list of strings to integers.
        e.g., 1,2,3 -> [1, 2, 3]
        """
        return [int(str_id) for str_id in qs.split(",")]

    def get_queryset(self):
        """Retrieve recipes for authenticated user"""
        # Get query parameters for tags and ingredients
        # They are string of comma-separated integers
        tags = self.request.query_params.get("tags")  # type: ignore
        ingredients = self.request.query_params.get("ingredients")  # type: ignore
        queryset = self.queryset
        if tags:
            tag_ids = self._params_to_ints(tags)
            queryset = queryset.filter(tags__id__in=tag_ids)

        if ingredients:
            ingredient_ids = self._params_to_ints(ingredients)
            queryset = queryset.filter(ingredients__id__in=ingredient_ids)

        return (
            queryset.filter(user=self.request.user).order_by("-id").distinct()
        )  # get unique items

    def get_serializer_class(self):
        """Return the serializer class for request."""
        if self.action == "list":
            return serializers.RecipeSerializer
        elif self.action == "upload_image":  # custom action
            return serializers.RecipeImageSerializer
        return self.serializer_class

    def perform_create(self, serializer):  # called when new recipe is created
        """Create a new recipe"""
        serializer.save(user=self.request.user)

    @action(methods=["POST"], detail=True, url_path="upload-image")
    def upload_image(self, request, pk=None):
        """Upload an image to a recipe"""
        recipe = self.get_object()
        serializer = self.get_serializer(recipe, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@extend_schema_view(
    list=extend_schema(
        parameters=[
            OpenApiParameter(
                "assigned_only",
                OpenApiTypes.INT,
                enum=[0, 1],  # only allows 0 and 1
                description="Filter by items assigned to recipes",
            )
        ]
    )
)  # extend the autogenerated schema
class BaseRecipeAttrViewSet(
    mixins.DestroyModelMixin,
    mixins.UpdateModelMixin,
    mixins.ListModelMixin,
    viewsets.GenericViewSet,
):
    """Base viewset for recipe attributes."""

    # Here we don't need ModelViewSet because it is not necessary. We only need the listing
    # functinality, using ModelViewSet is an overkill.
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]
    # ListModelMixin provides the list method
    # GenericViewSet provides the basic viewset functionality
    # We can also use mixins.CreateModelMixin to provide the create method
    # We can also use mixins.RetrieveModelMixin to provide the retrieve method
    # We can also use mixins.UpdateModelMixin to provide the update method
    # We can also use mixins.DestroyModelMixin to provide the destroy method

    def get_queryset(self):
        """Filter queryset by the authenticated user."""
        assigned_only = bool(int(self.request.query_params.get("assigned_only", 0)))  # type: ignore
        queryset = self.queryset
        if assigned_only:
            queryset = queryset.filter(recipe__isnull=False)  # type: ignore

        return queryset.filter(user=self.request.user).order_by("-name").distinct()  # type: ignore


class TagViewSet(BaseRecipeAttrViewSet):
    """Manage tags in the database"""

    serializer_class = serializers.TagSerializer
    queryset = Tag.objects.all()


class IngredientViewSet(BaseRecipeAttrViewSet):
    """Manage ingredients in the database"""

    serializer_class = serializers.IngredientSerializer
    queryset = Ingredient.objects.all()
